#!/bin/bash
pythran -march=native -O3 lapl1d_1.py
pythran -march=native -O3 lapl1d_2.py
pythran -march=native -O3 lapl2d_1.py
pythran -march=native -O3 lapl2d_2.py
pythran -march=native -O3 cl_1.py
pythran -march=native -O3 cl_2.py
#
for i in main*.py; do
    echo " " 
    echo $i
    echo "---"
    echo " "
    python3 $i
done
